name: dockerbuild

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: generate tag
        run: |-
            export PROJ_VERSION="5.16.6"
            echo "Project Version: $PROJ_VERSION"
            echo "TAG=$PROJ_VERSION-$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
            echo "SHORT_TAG=$PROJ_VERSION" >> $GITHUB_ENV

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.io/tremolosecurity/activemq-docker:latest
            docker.io/tremolosecurity/activemq-docker:${{ env.TAG }}
            docker.io/tremolosecurity/activemq-docker:${{ env.SHORT_TAG }}
            ghcr.io/tremolosecurity/activemq-docker:latest
            ghcr.io/tremolosecurity/activemq-docker:${{ env.TAG }}
            ghcr.io/tremolosecurity/activemq-docker:${{ env.SHORT_TAG }}